# Generated by Django 5.2.4 on 2025-08-22 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_category_options_remove_category_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
