# Generated by Django 5.2.4 on 2025-08-23 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_category_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('moderate_comments', 'Can moderate comments')]},
        ),
    ]
