# Generated by Django 5.2.4 on 2025-07-29 11:13

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/avatar/default.png', upload_to=apps.user.models.get_avatar_filename),
        ),
    ]
