# Generated by Django 5.2.4 on 2025-08-03 23:39

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/avatar/default/Ninguno.png', upload_to=apps.user.models.get_avatar_filename),
        ),
    ]
